repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      - id: ruff-check
        args: ["--fix"]
      - id: ruff-format

  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: python scripts/run_pyright.py
        language: python
        additional_dependencies:
          - "nbqa>=1.9,<2"
          - "numpy>=2.0,<3"
          - "pandas>=2.2,<3"
          - "pyright[nodejs]>=1.1.405,<2"
          - "pytest>=8,<9"
          - "scipy>=1.13,<2"
          - "streamlit>=1.40,<2"
        pass_filenames: false
