minimum_prek_version = "0.5.2"

[[repos]]
repo = "builtin"
hooks = [
  { id = "check-added-large-files", args = ["--maxkb=1000"] },
  { id = "check-merge-conflict" },
  { id = "check-toml" },
  { id = "check-yaml" },
  { id = "end-of-file-fixer" },
  { id = "trailing-whitespace" },
]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "ruff-check"
name = "ruff check"
language = "python"
language_version = "3.14"
entry = "ruff check --force-exclude"
args = ["--fix"]
additional_dependencies = ["ruff==0.16.7"]
types_or = ["python", "pyi", "jupyter"]

[[repos.hooks]]
id = "ruff-format"
name = "ruff format"
language = "python"
language_version = "3.14"
entry = "ruff format --force-exclude"
additional_dependencies = ["ruff==0.16.7"]
types_or = ["python", "pyi", "jupyter"]
